function Bz = calculate_Bz(z_pos, r_pos, t_curr, ...
    sol1, sol2, sol3, sol4, sol5, sol7, sol8, sol9, sol10, sol11, sol12, ...
    sol14, sol15, sol16, sol17, sol18, sol19, ...
    sol20, sol21, sol22, sol23, sol24, sol25, sol26, sol27, sol28, sol29, ...
    sol30, sol31, sol32, sol33, sol34, sol35, sol36, ...
    sol38, sol39, sol40, sol41, sol42, sol43, ...
    sol45, sol46, sol47, sol48, sol49, ...
    pulse_func)
    
    pulse_factor = pulse_func(t_curr);
    
    % Sum contributions from all 45 active transport solenoids
    % (Excludes steering magnets 6, 13, 37, 44)
    Bz = pulse_factor * (...
         solenoid_Bz(z_pos, r_pos, sol1) + solenoid_Bz(z_pos, r_pos, sol2) + ...
         solenoid_Bz(z_pos, r_pos, sol3) + solenoid_Bz(z_pos, r_pos, sol4) + ...
         solenoid_Bz(z_pos, r_pos, sol5) + solenoid_Bz(z_pos, r_pos, sol7) + ...
         solenoid_Bz(z_pos, r_pos, sol8) + solenoid_Bz(z_pos, r_pos, sol9) + ...
         solenoid_Bz(z_pos, r_pos, sol10) + solenoid_Bz(z_pos, r_pos, sol11) + ...
         solenoid_Bz(z_pos, r_pos, sol12) + solenoid_Bz(z_pos, r_pos, sol14) + ...
         solenoid_Bz(z_pos, r_pos, sol15) + solenoid_Bz(z_pos, r_pos, sol16) + ...
         solenoid_Bz(z_pos, r_pos, sol17) + solenoid_Bz(z_pos, r_pos, sol18) + ...
         solenoid_Bz(z_pos, r_pos, sol19) + solenoid_Bz(z_pos, r_pos, sol20) + ...
         solenoid_Bz(z_pos, r_pos, sol21) + solenoid_Bz(z_pos, r_pos, sol22) + ...
         solenoid_Bz(z_pos, r_pos, sol23) + solenoid_Bz(z_pos, r_pos, sol24) + ...
         solenoid_Bz(z_pos, r_pos, sol25) + solenoid_Bz(z_pos, r_pos, sol26) + ...
         solenoid_Bz(z_pos, r_pos, sol27) + solenoid_Bz(z_pos, r_pos, sol28) + ...
         solenoid_Bz(z_pos, r_pos, sol29) + solenoid_Bz(z_pos, r_pos, sol30) + ...
         solenoid_Bz(z_pos, r_pos, sol31) + solenoid_Bz(z_pos, r_pos, sol32) + ...
         solenoid_Bz(z_pos, r_pos, sol33) + solenoid_Bz(z_pos, r_pos, sol34) + ...
         solenoid_Bz(z_pos, r_pos, sol35) + solenoid_Bz(z_pos, r_pos, sol36) + ...
         solenoid_Bz(z_pos, r_pos, sol38) + solenoid_Bz(z_pos, r_pos, sol39) + ...
         solenoid_Bz(z_pos, r_pos, sol40) + solenoid_Bz(z_pos, r_pos, sol41) + ...
         solenoid_Bz(z_pos, r_pos, sol42) + solenoid_Bz(z_pos, r_pos, sol43) + ...
         solenoid_Bz(z_pos, r_pos, sol45) + solenoid_Bz(z_pos, r_pos, sol46) + ...
         solenoid_Bz(z_pos, r_pos, sol47) + solenoid_Bz(z_pos, r_pos, sol48) + ...
         solenoid_Bz(z_pos, r_pos, sol49));
end

function Bz = solenoid_Bz(z, r, sol)
    in_radius = r <= sol.R;
    z_factor = 0.5 * (tanh(2*(z - (sol.z_c - sol.L/2))/sol.L) - ...
                      tanh(2*(z - (sol.z_c + sol.L/2))/sol.L));
    Bz = sol.B * in_radius .* z_factor;
end

